name: cw_application_9
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.5.3

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  assets:
    - assets/
